NPM_TOKEN: ENC[AES256_GCM,data:kEnvWQK1pQ3Xfa8q975HwgKiottpiOR2msK+OJElml1Uj4h9G0F9nA==,iv:vSvCssT2luSt3oC6JB4EIt/GBfyQsFJo8QQt5y3yIc8=,tag:UyOzz2XOX44PFF8RiyxMpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL3krK281R3BaQzFRZzBR
            Q0x6UlBEOXJ3K0VzeXl0WU5RWmxYTXZIL2pvCmdQZGFNc0FDT3N0S0dyU3A3Y1A0
            Sy95aTR4ajZYdnY0WnQxUGRtVmZwZVUKLS0tIFYzb0U4U21ydUxTQTB6ZTBaUHE0
            cEJvWHRod1Fyd3lacjl1SnlLbGlacEkKucvHr5yiHtXEZbyaAeImzKwUbolLXoVw
            7izpg9CC1+jRefp7ZfP3NZIM6EaAw+TejSuNnaYAQNRhStxXJOhc8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhslnakk54dn5vd7q7hjuemrchwxtka0ux8nkvm4psp9u3g9hsxsjzvsdz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3g5Mmo4TDZnaTBtZzVh
            eUpLSUxhdmxad3VDZExiMHFnYTV5ZTk4OTNvCk9JM0xUSjF2bmFVbDBjMU5qbFhL
            ZGQ4RjB4WExNNkVpbEwyVFIrSmcvS2cKLS0tIGl0Sjd1enhFcXB6d0o1WEdBN1Rp
            T0dIWkFlQjNucHVON1hoelNraC92ckkKCkZ1hJbi0Gy8gJaoeGOAUkrzChZF7bR5
            k4g17Q2JMlJQOztPJL2kD3X2TcxkGDD+2I/zwPdWxRZNYvLH7MwZSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaWtkZSsrMnRiOXZiTjVZ
            cUZyTm1DV2VWMEc2c2tSZ0ZySGU2VWJkclFzCktWbUdiUDFoRk5DUlQ3cEZyS3Q3
            ODJjTHdiQklrRVZDb2ZVaE1NTjRxOUEKLS0tIHZHZjJXM2tIRXJMV1I3YVp1VzE0
            eDJ2dXBON05hODJKai96MkdCYXllNFEKE/N1+7jNJW6sXDtxqOinVfJ7Kz6LeAN4
            sYD4msYjj01xRa0vwwX2G210ezpL9M7YuBUws3nsRhHXTXs/g0zRsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1llqq3jcd8kk0w92x9mgwdswymtjd967ydghvdvqr2djxwakmgydquytfdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ25uN3JxNHh6T1pSVzVD
            YmErNmpqbitJNHVIUkVUSTVKdXFSY29YRFhFClFEZ2hvNHMyWGJFeG9IQ1BtS3lz
            UnQyTUtHblNQaTBTekx0bWtnUWZtVFUKLS0tIFdFTWRmb1Y1YURZbFZ5Wi8zZG9O
            a2RyUThqVWQ0eGY1SlM4c042WU1pWFUKYkCEmlY+E8G3M1bfoiWVNihCPHK/K4Wf
            L8JyaASROZT3wulze/wkXvkLbIWKIkfj8/N54yRhT5vQ4VAV0nEAXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ar5d2qsnz5tjmm9xx0h5wl2n7m6f3l4mr3fhm400zulggmh6xsjst65ygm
    lastmodified: "2026-09-23T05:18:01Z"
    mac: ENC[AES256_GCM,data:fTAKCAxv7EDynGfXrmGiMTBLcbQCIxgz6FvdtIFeAzn7Mfr5yRI0ChveMsIlpQFI6RUKgV2PKd7MAaW6AF3JU11Va3MCnsmP5mveFjbwJr7EbrtDPCW1YO2XmOC7eHbw3zvmStU2zO1nJ/a+MILaLp40tpRdCXy43m/pvB4F4Ak=,iv:+ZyabgW3B9rKdiDQtUroPQy6EEu9ErX0YdJbmP4LJ7U=,tag:SX/WxHmxvsyuNmRyl7fawg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
