#!/usr/bin/env bun
// Build @zabaca/croft/read for Node and Bun (DESIGN.md §2, §10): dist/read.js + dist/read.d.ts.
//
// The CLI ships TypeScript source, but apps import this helper from Node too, and Node refuses to strip
// types from files under node_modules (ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING). So src/read.ts is
// bundled into ESM with every npm package left external (@duckdb/node-api must be the app's own copy: it
// loads a native binding), the equivalent of
//   bun build src/read.ts --target=node --format=esm --packages=external --outdir dist --splitting
// Splitting puts direct mode, the only code that needs @duckdb/node-api, into a chunk that read.js imports
// on first use: a hosted app that only talks to croft serve never loads the binding.
// The declaration file is written by hand from src/read-types.ts: tsc would emit declarations for every
// internal module read.ts imports, with .ts import paths a consumer cannot resolve.
//
// Usage: bun scripts/build-read.ts [--outdir <dir>]   (default: dist/ next to package.json)
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const at = args.indexOf("--outdir");
const outdir = resolve(pkgRoot, at >= 0 && args[at + 1] ? args[at + 1]! : "dist");

function fail(message: string): never {
  console.error(`build-read: ${message}`);
  process.exit(1);
}

mkdirSync(outdir, { recursive: true });
for (const f of readdirSync(outdir)) {
  if (f === "read.js" || f === "read.d.ts" || /^read-[a-z0-9]+\.js$/.test(f)) rmSync(join(outdir, f), { force: true });
}

const result = await Bun.build({
  entrypoints: [join(pkgRoot, "src", "read.ts")],
  outdir,
  target: "node",
  format: "esm",
  packages: "external",
  splitting: true,
  naming: { entry: "[name].[ext]", chunk: "read-[hash].[ext]" },
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  fail("bun build failed");
}

// The bundle must run on Node: no Bun globals and no bun: modules may survive bundling, and the only
// package it may import is @duckdb/node-api (never from the entry, which server-only apps load).
const outputs = result.outputs.map((o) => o.path);
let bytes = 0;
for (const file of outputs) {
  const js = readFileSync(file, "utf8");
  bytes += Buffer.byteLength(js);
  const name = file.slice(outdir.length + 1);
  const bunOnly = js.match(/\bBun\.[A-Za-z]+|["']bun:[a-z]+["']/);
  if (bunOnly) fail(`${name} references a Bun-only API (${bunOnly[0]}); read.ts must use node: modules only`);
  const packages = staticImports(js).filter((s) => !s.startsWith("node:") && !s.startsWith("./"));
  const allowed = name === "read.js" ? [] : ["@duckdb/node-api"];
  const bad = packages.filter((s) => !allowed.includes(s));
  if (bad.length) fail(`${name} imports ${[...new Set(bad)].join(", ")} at load time; only direct mode may import @duckdb/node-api`);
}

/** Specifiers of the static `import ... from "x"` statements of an ESM file. */
function staticImports(js: string): string[] {
  return [...js.matchAll(/^import\b[^;]*?from\s*["']([^"']+)["']/gm)].map((m) => m[1]!);
}

const types = readFileSync(join(pkgRoot, "src", "read-types.ts"), "utf8").trim();
const dts = `// Generated by scripts/build-read.ts from src/read-types.ts and src/read.ts; do not edit.
${types}

/** What query() throws: an Error with a stable \`code\` (e.g. SERVE_UNAVAILABLE, QUERY_TOO_MANY_ROWS, DB_BUSY). */
export interface ReadError extends Error {
  readonly code: string;
  readonly problem: {
    severity: "error" | "warning" | "info";
    code: string;
    message: string;
    hint: string;
    docs: string;
    retryable?: boolean;
    details?: Record<string, unknown>;
  };
}

/**
 * Run one SELECT (or DESCRIBE/SUMMARIZE/SHOW) against the croft project's warehouse and return its rows.
 * \`params\` bind to $1, $2, ... Uses croft serve when one is configured ({ url }, CROFT_URL) or running
 * (.croft/serve.json), and otherwise reads the DuckDB file directly, read-only. More rows than \`limit\`
 * (default 10,000) throw QUERY_TOO_MANY_ROWS; results are never truncated. Throws a ReadError.
 */
export declare function query<T extends Record<string, unknown> = Record<string, unknown>>(
  sql: string, params?: unknown[], options?: ReadOptions,
): Promise<T[]>;
`;
writeFileSync(join(outdir, "read.d.ts"), dts);

const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;
console.log(`built ${join(outdir, "read.js")} and ${outputs.length - 1} chunk(s), ${kb(bytes)}, and read.d.ts`);
